### ISSUE TITLE
Walk up small slopes

### ISSUE THREAD

**Issue by AntonioNoack** [bodhid/voxtopolis-issues#35]
Hey :),

I think you should be able to walk (without needing to jump) up small slopes.
Example:
![image](https://github.com/bodhid/voxtopolis-issues/assets/20659579/3d1f3886-f013-40d1-a995-769fdbfe7326)

In Minecraft, the max step height is 0.5 blocks for example, maybe something like that.

**Comment by bodhid** [comment]
@AntonioNoack This should hopefully be addressed with the slope check added in 0.2.12 build!
