### ISSUE TITLE
I fell through the ground

### ISSUE THREAD

**Issue by Lampe2020** [bodhid/voxtopolis-issues#84]
I somehow managed to fall into the mountain near spawn in the default world . I tried to climb up, got stuck on a ledge trying to climb up and then suddenly found myself inside the mountain. When I tried to break back out I basically built blocks of stone wherever I destroyed the dirt (because from the outside it is supposed to look like it's massive and not hollow). I tried to get out of the mountain for quite a while before a frog that had also made its way inside the mountain killed me.   
If I knew where to find the world save I would have attached it here, but it seems like the world isn't even saved contrary to the description given in the builds channel, as I, when rejoining the world, was back at the spawn pillar even though I had wandered off before closing the world.   
   
[EDIT]: I'm running version 0.5.97, at the time of writing the newest in the \#builds channel. .

**Comment by bodhid** [comment]
There is a step system that can misbehave. it is supposed to help the player walk up stairs of small voxels without getting stuck. But has many unintended side effects, like pushing a player up fast and through geometry. I'll take a look at a better system!

**Comment by Lampe2020** [comment]
I was actually ontop of the curve of the ledge (almost fully up, only a handful of voxels below the top surface) and got pushed diagonally down and forwards and fell through the corner. Roughly like the sketch below: 
![bild](https://github.com/user-attachments/assets/9babe814-a733-449d-9a24-4c3309d6c593)
